have_currencies = [
    'Chaos Orb',
    'Divine Orb',
]

want_currencies = [
    # Basic Currency
    'Rogue\'s Marker',
    'Orb of Transmutation',
    'Orb of Augmentation',
    'Orb of Chance',
    'Orb of Alteration',
    'Chromatic Orb',
    'Jeweller\'s Orb',
    'Orb of Fusing',
    'Orb of Alchemy',
    'Chaos Orb',
    'Orb of Scouring',
    'Orb of Regret',
    'Vaal Orb',
    'Orb of Binding',
    'Instilling Orb',
    'Orb of Unmaking',
    'Blessed Orb',
    'Orb of Horizons',
    'Enkindling Orb',
    'Regal Orb',
    'Divne Vessel',
    'Exalted Orb',
    'Ancient Orb',
    'Stacked Deck',
    'Harbinger\'s Orb',
    'Valdo\s Puzzle Box',
    'Divine Orb',
    'Orb of Annulment',
    'Voidburn Reliquary Key',
    'Reflecting Mist',
    'Tempering Orb',
    'Tailoring Orb',
    'Fracturing Orb',
    'Veiled Orb',
    'Sacred Orb',
    'Hinekora\'s Lock',
    'Mirror of Kalandra',
    'Eldritch Chaos Orb',
    'Eldritch Exalted Orb',
    'Eldritch Orb of Annulment',
    'Lesser Eldritch Ember',
    'Lesser Eldritch Ichor',
    'Greater Eldritch Ember',
    'Greater Eldritch Ichor',
    'Grand Eldritch Ember',
    'Grand Eldritch Ichor',
    'Exceptional Eldritch Ember',
    'Exceptional Eldritch Ichor',
    'Orb of Conflict',
    'Fracturing Shard',
    'Mirror Shard',
    'Cartographer\'s Chisel',
    'Gemcutter\'s Prism',
    'Maven\'s Chisel of Procurement',
    'Maven\'s Chisel of Proliferation',
    'Maven\'s Chisel of Avarice',
    'Maven\'s Chisel of Divination',
    'Maven\'s Chisel of Scarabs',

]
